
########################################################################################################################################################################################################################################################################################################~{#
#//////|   Templates   |////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////g2#
########################################################################################################################################################################################################################################################################################################~}#

<BoxButton@MarginButton>
  font_name:        "RobotoMono-Regular"
  font_size:        14
  background_color: (0.5, 0.85, 0.75, 0.8)
  color:            (0.7, 0.78,  0.8, 0.9)

<FloatButton@BoxButton>
  size_hint:        (None, None)
  size:             (150, 150)
  margin:           (30, 30, 30, 30)
  background_color: (0.5, 0.6,  0.9, 0.9)
  color:            (0.7, 0.72, 0.8, 0.9)


########################################################################################################################################################################################################################################################################################################~{#
#//////|   DemoLayout   |///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////g2#
########################################################################################################################################################################################################################################################################################################~}#

<DemoLayout>
  orientation: "vertical"

  ########################
  ###  BoxLayout Demo  ###
  ########################

  Label:
    text:      "BoxLayout"
    size_hint: (1, 0.05)

  MarginBoxLayout:
    size_hint:        (1, 0.2)
    background_color: (0.3, 0.7, 0.65, 0.3)

    BoxButton:
      id:        boxButton
      size_hint: (0.5, 1)
      margin:    ("0%", "0%", "0%", "0%")
    BoxButton:
      text:      "size_hint: (0.5, 1)"
      size_hint: (0.5, 1)

  ##########################
  ###  FloatLayout Demo  ###
  ##########################

  Label:
    id:        floatLayout_Label
    text:      "FloatLayout"
    size_hint: (1, 0.05)

  MarginFloatLayout:
    id:               floatLayout
    size_hint:        (1, 0.7)
    background_color: (0.3, 0.4, 0.7, 0.3)

    FloatButton:
      text:      "x:Left\ny:Top"
      pos_hint:  {"left": 1, "top": 1}
    FloatButton:
      text:      "x:Center\ny:Top"
      pos_hint:  {"center_x": 0.5, "top": 1}
    FloatButton:
      text:      "x:Right\ny:Top"
      pos_hint:  {"right": 1, "top": 1}
    FloatButton:
      text:      "x:Left\ny:Center"
      pos_hint:  {"left": 1, "center_y": 0.5}
    FloatButton:
      text:      "x:Center\ny:Center"
      pos_hint:  {"center_x": 0.5, "center_y": 0.5}
    FloatButton:
      text:      "x:Right\ny:Center"
      pos_hint:  {"right": 1, "center_y": 0.5}
    FloatButton:
      text:      "x:Left\ny:Bottom"
      pos_hint:  {"left": 1, "bottom": 1}
    FloatButton:
      text:      "x:Center\ny:Bottom"
      pos_hint:  {"center_x": 0.5, "bottom": 1}
    FloatButton:
      text:      "x:Right\ny:Bottom"
      pos_hint:  {"right": 1, "bottom": 1}

